name: IP File Distribution

on:
  workflow_dispatch:  # Manual execution via GitHub interface
  schedule:
    - cron: '0 * * * *'  # Runs every 60 minutes
  push:  # Trigger when the repository is updated
    branches:
      - main  # Replace 'main' with your default branch if different

jobs:
  send-files:
    runs-on: ubuntu-latest

    env:
      CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      EXPORT_URL: "https://raw.githubusercontent.com/ircfspace/cf2dns/refs/heads/master/list/export.json"
      IPV4_URL: "https://raw.githubusercontent.com/ircfspace/cf2dns/refs/heads/master/list/ipv4.json"
      IPV6_URL: "https://raw.githubusercontent.com/ircfspace/cf2dns/refs/heads/master/list/ipv6.json"
      FULL_URL: "https://raw.githubusercontent.com/ircfspace/warpkey/main/plus/full"
      LITE_URL: "https://raw.githubusercontent.com/ircfspace/warpkey/main/plus/lite"

    steps:
      # Step 1: Initialize the repository
      - name: Initialize Repository
        uses: actions/checkout@v3  # Use the latest stable version

      # Step 2: Download Files
      - name: Download Files
        run: |
          curl --retry 3 -o export.json $EXPORT_URL
          curl --retry 3 -o ipv4.json $IPV4_URL
          curl --retry 3 -o ipv6.json $IPV6_URL
          curl --retry 3 -o full $FULL_URL
          curl --retry 3 -o lite $LITE_URL

      # Step 3: Send Files to Telegram
      - name: Send Files to Telegram
        run: |
          for file in export.json ipv4.json ipv6.json full lite; do
            case $file in
              export.json)
                caption="📂 Export Data File: Comprehensive dataset for analysis." ;;
              ipv4.json)
                caption="🌐 IPv4 Addresses." ;;
              ipv6.json)
                caption="🌍 IPv6 Addresses." ;;
              full)
                caption="📋 Full File: Detailed data file for broad analysis." ;;
              lite)
                caption="📑 Lite File: Streamlined dataset for focused analysis." ;;
            esac

            curl --retry 3 -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendDocument" \
              -F chat_id="$CHAT_ID" \
              -F document=@$file \
              -F caption="$caption"
          done
